version: '3'

services:
    frontend:
      container_name: front-container
      restart: always
      build: ./client
      ports: 
        - "3000:3000"
    backend:
      container_name: back-container
      restart: always
      build: .
      ports:
        - "5000:5000"

